import type { SheetCellModel, SpreadsheetConfig } from './spreadsheetTypes';

export type SeatGeekCaseStudyInputs = {
  primaryRevenueY1: number;
  primaryRevenueY2: number;
  primaryRevenueY3: number;
  secondaryRevenueY1: number;
  secondaryRevenueY2: number;
  secondaryRevenueY3: number;
  marketUpliftRevenueY1: number;
  marketUpliftRevenueY2: number;
  marketUpliftRevenueY3: number;
  pricingRevenueY1: number;
  pricingRevenueY2: number;
  pricingRevenueY3: number;
  semCostY1: number;
  semCostY2: number;
  semCostY3: number;
  minimumGuaranteeY1: number;
  guaranteeGrowthPct: number;
  revSharePct: number;
  otherPersonnelY1: number;
  otherPersonnelY2: number;
  otherPersonnelY3: number;
  discountRatePct: number;
};

export type SeatGeekCaseStudyOutputs = {
  revenueTotals: number[];
  minimumGuarantee: number[];
  revShare: number[];
  blendedCosts: number[];
  ebitda: number[];
  ebitdaMarginPct: number[];
  y3Npv: number;
  paybackPeriodYears: number;
};

export const seatGeekCaseStudyDefaultInputs: SeatGeekCaseStudyInputs = {
  primaryRevenueY1: 10,
  primaryRevenueY2: 12,
  primaryRevenueY3: 14,
  secondaryRevenueY1: 100,
  secondaryRevenueY2: 122,
  secondaryRevenueY3: 145,
  marketUpliftRevenueY1: 7,
  marketUpliftRevenueY2: 12,
  marketUpliftRevenueY3: 18,
  pricingRevenueY1: 2,
  pricingRevenueY2: 3,
  pricingRevenueY3: 4,
  semCostY1: 14.2,
  semCostY2: 15.6,
  semCostY3: 17.1,
  minimumGuaranteeY1: 80,
  guaranteeGrowthPct: 2,
  revSharePct: 45,
  otherPersonnelY1: 0.9,
  otherPersonnelY2: 1.1,
  otherPersonnelY3: 1.4,
  discountRatePct: 12,
};

export const seatGeekCaseStudySheetConfig: SpreadsheetConfig = {
  documentTitle: 'SeatGeek Case Study',
  columnLabels: ['A', 'B', 'C', 'D'],
  rowNumbers: Array.from({ length: 15 }, (_, index) => 12 + index),
  columnWidths: [
    'minmax(268px, 2.2fr)',
    'minmax(106px, 0.9fr)',
    'minmax(122px, 1fr)',
    'minmax(132px, 1.08fr)',
  ],
  rowHeights: [
    '54px',
    '54px',
    '42px',
    '52px',
    '52px',
    '52px',
    '52px',
    '52px',
    '52px',
    '52px',
    '52px',
    '52px',
    '52px',
    '52px',
    '54px',
  ],
  className: 'is-case-study-sheet',
  overlayFade: 'right',
  showFormulaBar: false,
};

function roundTo(value: number, decimals = 2) {
  const factor = 10 ** decimals;
  return Math.round(value * factor) / factor;
}

function formatOneDecimal(value: number) {
  return roundTo(value, 1).toFixed(1);
}

function computePaybackPeriod(ebitda: number[], commitmentBase: number) {
  let cumulative = 0;

  for (let index = 0; index < ebitda.length; index += 1) {
    const nextCumulative = cumulative + ebitda[index];

    if (nextCumulative >= commitmentBase) {
      const remaining = Math.max(commitmentBase - cumulative, 0);
      return roundTo(index + remaining / Math.max(ebitda[index], 0.001), 1);
    }

    cumulative = nextCumulative;
  }

  return roundTo(ebitda.length, 1);
}

function allGroups(groups: string | string[]) {
  const normalized = Array.isArray(groups) ? groups : [groups];
  return [...normalized, 'case-study-all'];
}

export function calculateSeatGeekCaseStudyOutputs(
  inputs: SeatGeekCaseStudyInputs
): SeatGeekCaseStudyOutputs {
  const revenueTotals = [
    inputs.primaryRevenueY1 +
      inputs.secondaryRevenueY1 +
      inputs.marketUpliftRevenueY1 +
      inputs.pricingRevenueY1,
    inputs.primaryRevenueY2 +
      inputs.secondaryRevenueY2 +
      inputs.marketUpliftRevenueY2 +
      inputs.pricingRevenueY2,
    inputs.primaryRevenueY3 +
      inputs.secondaryRevenueY3 +
      inputs.marketUpliftRevenueY3 +
      inputs.pricingRevenueY3,
  ].map((value) => roundTo(value, 1));

  const minimumGuarantee = [
    inputs.minimumGuaranteeY1,
    inputs.minimumGuaranteeY1 * (1 + inputs.guaranteeGrowthPct / 100),
    inputs.minimumGuaranteeY1 * (1 + inputs.guaranteeGrowthPct / 100) ** 2,
  ].map((value) => roundTo(value, 1));

  const revShare = revenueTotals.map((value) =>
    roundTo(value * (inputs.revSharePct / 100), 1)
  );

  const blendedCosts = [
    inputs.semCostY1 + Math.max(minimumGuarantee[0], revShare[0]) + inputs.otherPersonnelY1,
    inputs.semCostY2 + Math.max(minimumGuarantee[1], revShare[1]) + inputs.otherPersonnelY2,
    inputs.semCostY3 + Math.max(minimumGuarantee[2], revShare[2]) + inputs.otherPersonnelY3,
  ].map((value) => roundTo(value, 1));

  const ebitda = revenueTotals.map((value, index) =>
    roundTo(value - blendedCosts[index], 1)
  );

  const ebitdaMarginPct = ebitda.map((value, index) =>
    roundTo((value / Math.max(revenueTotals[index], 0.001)) * 100, 1)
  );

  const discountRate = inputs.discountRatePct / 100;
  const y3Npv = roundTo(
    ebitda.reduce(
      (sum, yearValue, index) => sum + yearValue / (1 + discountRate) ** (index + 1),
      0
    ),
    1
  );

  return {
    revenueTotals,
    minimumGuarantee,
    revShare,
    blendedCosts,
    ebitda,
    ebitdaMarginPct,
    y3Npv,
    paybackPeriodYears: computePaybackPeriod(ebitda, minimumGuarantee[0]),
  };
}

export function buildSeatGeekCaseStudyCells(
  inputs: SeatGeekCaseStudyInputs,
  outputs: SeatGeekCaseStudyOutputs
): SheetCellModel[] {
  return [
    {
      id: 'A12',
      address: 'A12',
      row: 12,
      col: 1,
      colSpan: 4,
      variant: 'title',
      label: 'Partnership P&L model',
      className: 'is-case-study-title',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'A13',
      address: 'A13',
      row: 13,
      col: 1,
      variant: 'summary',
      label: 'Y3 EBITDA Margin',
      value: formatOneDecimal(outputs.ebitdaMarginPct[2]),
      suffix: '%',
      tone: 'formula',
      align: 'right',
      formula: '=D26/D15',
      highlightGroup: allGroups('scenario'),
      emphasisLevel: 'high',
    },
    {
      id: 'B13',
      address: 'B13',
      row: 13,
      col: 2,
      variant: 'summary',
      label: 'Payback',
      value: formatOneDecimal(outputs.paybackPeriodYears),
      suffix: ' yrs',
      tone: 'formula',
      align: 'right',
      formula:
        '=IF(B26>=B22,1,IF(B26+C26>=B22,1+((B22-B26)/C26),2+((B22-B26-C26)/D26)))',
      highlightGroup: allGroups('scenario'),
      emphasisLevel: 'high',
    },
    {
      id: 'C13',
      address: 'C13',
      row: 13,
      col: 3,
      variant: 'summary',
      label: 'Y3 NPV',
      value: formatOneDecimal(outputs.y3Npv),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=B26/(1+12%) + C26/(1+12%)^2 + D26/(1+12%)^3',
      highlightGroup: allGroups('scenario'),
      emphasisLevel: 'high',
    },
    {
      id: 'A14',
      address: 'A14',
      row: 14,
      col: 1,
      variant: 'table-header',
      label: 'P&L line item',
      tone: 'neutral',
    },
    {
      id: 'B14',
      address: 'B14',
      row: 14,
      col: 2,
      variant: 'table-header',
      label: 'Y1',
      tone: 'neutral',
      align: 'right',
    },
    {
      id: 'C14',
      address: 'C14',
      row: 14,
      col: 3,
      variant: 'table-header',
      label: 'Y2',
      tone: 'neutral',
      align: 'right',
    },
    {
      id: 'D14',
      address: 'D14',
      row: 14,
      col: 4,
      variant: 'table-header',
      label: 'Y3',
      tone: 'neutral',
      align: 'right',
    },
    {
      id: 'A15',
      address: 'A15',
      row: 15,
      col: 1,
      variant: 'section-header',
      label: 'Revenue',
      tone: 'neutral',
      highlightGroup: allGroups('deal-scale'),
    },
    {
      id: 'B15',
      address: 'B15',
      row: 15,
      col: 2,
      variant: 'section-header',
      value: formatOneDecimal(outputs.revenueTotals[0]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=SUM(B16:B19)',
      highlightGroup: allGroups('deal-scale'),
      emphasisLevel: 'high',
    },
    {
      id: 'C15',
      address: 'C15',
      row: 15,
      col: 3,
      variant: 'section-header',
      value: formatOneDecimal(outputs.revenueTotals[1]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=SUM(C16:C19)',
      highlightGroup: allGroups('deal-scale'),
      emphasisLevel: 'high',
    },
    {
      id: 'D15',
      address: 'D15',
      row: 15,
      col: 4,
      variant: 'section-header',
      value: formatOneDecimal(outputs.revenueTotals[2]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=SUM(D16:D19)',
      highlightGroup: allGroups('deal-scale'),
      emphasisLevel: 'high',
    },
    {
      id: 'A16',
      address: 'A16',
      row: 16,
      col: 1,
      variant: 'text',
      label: 'Primary Revenues',
      tone: 'neutral',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'B16',
      address: 'B16',
      row: 16,
      col: 2,
      variant: 'metric',
      tone: 'input',
      editableKey: 'primaryRevenueY1',
      editableValue: inputs.primaryRevenueY1,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'C16',
      address: 'C16',
      row: 16,
      col: 3,
      variant: 'metric',
      tone: 'input',
      editableKey: 'primaryRevenueY2',
      editableValue: inputs.primaryRevenueY2,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'D16',
      address: 'D16',
      row: 16,
      col: 4,
      variant: 'metric',
      tone: 'input',
      editableKey: 'primaryRevenueY3',
      editableValue: inputs.primaryRevenueY3,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'A17',
      address: 'A17',
      row: 17,
      col: 1,
      variant: 'text',
      label: 'F2F + Broker Secondary',
      tone: 'neutral',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'B17',
      address: 'B17',
      row: 17,
      col: 2,
      variant: 'metric',
      tone: 'input',
      editableKey: 'secondaryRevenueY1',
      editableValue: inputs.secondaryRevenueY1,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'C17',
      address: 'C17',
      row: 17,
      col: 3,
      variant: 'metric',
      tone: 'input',
      editableKey: 'secondaryRevenueY2',
      editableValue: inputs.secondaryRevenueY2,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'D17',
      address: 'D17',
      row: 17,
      col: 4,
      variant: 'metric',
      tone: 'input',
      editableKey: 'secondaryRevenueY3',
      editableValue: inputs.secondaryRevenueY3,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'A18',
      address: 'A18',
      row: 18,
      col: 1,
      variant: 'text',
      label: 'Market Uplift: Indirect Revenues',
      tone: 'neutral',
      highlightGroup: allGroups('stat-model'),
    },
    {
      id: 'B18',
      address: 'B18',
      row: 18,
      col: 2,
      variant: 'metric',
      tone: 'input',
      editableKey: 'marketUpliftRevenueY1',
      editableValue: inputs.marketUpliftRevenueY1,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: allGroups('stat-model'),
      emphasisLevel: 'high',
    },
    {
      id: 'C18',
      address: 'C18',
      row: 18,
      col: 3,
      variant: 'metric',
      tone: 'input',
      editableKey: 'marketUpliftRevenueY2',
      editableValue: inputs.marketUpliftRevenueY2,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: allGroups('stat-model'),
      emphasisLevel: 'high',
    },
    {
      id: 'D18',
      address: 'D18',
      row: 18,
      col: 4,
      variant: 'metric',
      tone: 'input',
      editableKey: 'marketUpliftRevenueY3',
      editableValue: inputs.marketUpliftRevenueY3,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: allGroups('stat-model'),
      emphasisLevel: 'high',
    },
    {
      id: 'A19',
      address: 'A19',
      row: 19,
      col: 1,
      variant: 'text',
      label: 'Pricing (SeatGeek IQ) Revenues',
      tone: 'neutral',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'B19',
      address: 'B19',
      row: 19,
      col: 2,
      variant: 'metric',
      tone: 'input',
      editableKey: 'pricingRevenueY1',
      editableValue: inputs.pricingRevenueY1,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'C19',
      address: 'C19',
      row: 19,
      col: 3,
      variant: 'metric',
      tone: 'input',
      editableKey: 'pricingRevenueY2',
      editableValue: inputs.pricingRevenueY2,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'D19',
      address: 'D19',
      row: 19,
      col: 4,
      variant: 'metric',
      tone: 'input',
      editableKey: 'pricingRevenueY3',
      editableValue: inputs.pricingRevenueY3,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'A20',
      address: 'A20',
      row: 20,
      col: 1,
      variant: 'section-header',
      label: 'COGS + Fixed Costs',
      tone: 'neutral',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'B20',
      address: 'B20',
      row: 20,
      col: 2,
      variant: 'section-header',
      value: formatOneDecimal(outputs.blendedCosts[0]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=B21+B24+B25',
      highlightGroup: 'case-study-all',
      emphasisLevel: 'high',
    },
    {
      id: 'C20',
      address: 'C20',
      row: 20,
      col: 3,
      variant: 'section-header',
      value: formatOneDecimal(outputs.blendedCosts[1]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=C21+C24+C25',
      highlightGroup: 'case-study-all',
      emphasisLevel: 'high',
    },
    {
      id: 'D20',
      address: 'D20',
      row: 20,
      col: 4,
      variant: 'section-header',
      value: formatOneDecimal(outputs.blendedCosts[2]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=D21+D24+D25',
      highlightGroup: 'case-study-all',
      emphasisLevel: 'high',
    },
    {
      id: 'A21',
      address: 'A21',
      row: 21,
      col: 1,
      variant: 'text',
      label: 'Minimum Guarantee / Capital Commitment',
      tone: 'neutral',
      highlightGroup: allGroups('capital-commit'),
    },
    {
      id: 'B21',
      address: 'B21',
      row: 21,
      col: 2,
      variant: 'metric',
      tone: 'input',
      editableKey: 'minimumGuaranteeY1',
      editableValue: inputs.minimumGuaranteeY1,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: allGroups('capital-commit'),
      emphasisLevel: 'high',
    },
    {
      id: 'C21',
      address: 'C21',
      row: 21,
      col: 3,
      variant: 'metric',
      value: formatOneDecimal(outputs.minimumGuarantee[1]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=B21*(1+2%)',
      highlightGroup: allGroups('capital-commit'),
      emphasisLevel: 'high',
    },
    {
      id: 'D21',
      address: 'D21',
      row: 21,
      col: 4,
      variant: 'metric',
      value: formatOneDecimal(outputs.minimumGuarantee[2]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=C21*(1+2%)',
      highlightGroup: allGroups('capital-commit'),
      emphasisLevel: 'high',
    },
    {
      id: 'A22',
      address: 'A22',
      row: 22,
      col: 1,
      variant: 'text',
      label: 'Rev Share at 45%',
      tone: 'neutral',
      highlightGroup: allGroups('rev-share'),
    },
    {
      id: 'B22',
      address: 'B22',
      row: 22,
      col: 2,
      variant: 'metric',
      value: formatOneDecimal(outputs.revShare[0]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=B15*45%',
      highlightGroup: allGroups('rev-share'),
      emphasisLevel: 'high',
    },
    {
      id: 'C22',
      address: 'C22',
      row: 22,
      col: 3,
      variant: 'metric',
      value: formatOneDecimal(outputs.revShare[1]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=C15*45%',
      highlightGroup: allGroups('rev-share'),
      emphasisLevel: 'high',
    },
    {
      id: 'D22',
      address: 'D22',
      row: 22,
      col: 4,
      variant: 'metric',
      value: formatOneDecimal(outputs.revShare[2]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=D15*45%',
      highlightGroup: allGroups('rev-share'),
      emphasisLevel: 'high',
    },
    {
      id: 'A23',
      address: 'A23',
      row: 23,
      col: 1,
      variant: 'text',
      label: 'Rev Share vs Minimum Guarantee',
      tone: 'neutral',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'B23',
      address: 'B23',
      row: 23,
      col: 2,
      variant: 'metric',
      value: formatOneDecimal(Math.max(outputs.minimumGuarantee[0], outputs.revShare[0])),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=MAX(B21,B22)',
      highlightGroup: 'case-study-all',
      emphasisLevel: 'high',
    },
    {
      id: 'C23',
      address: 'C23',
      row: 23,
      col: 3,
      variant: 'metric',
      value: formatOneDecimal(Math.max(outputs.minimumGuarantee[1], outputs.revShare[1])),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=MAX(C21,C22)',
      highlightGroup: 'case-study-all',
      emphasisLevel: 'high',
    },
    {
      id: 'D23',
      address: 'D23',
      row: 23,
      col: 4,
      variant: 'metric',
      value: formatOneDecimal(Math.max(outputs.minimumGuarantee[2], outputs.revShare[2])),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=MAX(D21,D22)',
      highlightGroup: 'case-study-all',
      emphasisLevel: 'high',
    },
    {
      id: 'A24',
      address: 'A24',
      row: 24,
      col: 1,
      variant: 'text',
      label: 'Ads & Marketing',
      tone: 'neutral',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'B24',
      address: 'B24',
      row: 24,
      col: 2,
      variant: 'metric',
      tone: 'input',
      editableKey: 'semCostY1',
      editableValue: inputs.semCostY1,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'C24',
      address: 'C24',
      row: 24,
      col: 3,
      variant: 'metric',
      tone: 'input',
      editableKey: 'semCostY2',
      editableValue: inputs.semCostY2,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'D24',
      address: 'D24',
      row: 24,
      col: 4,
      variant: 'metric',
      tone: 'input',
      editableKey: 'semCostY3',
      editableValue: inputs.semCostY3,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'A25',
      address: 'A25',
      row: 25,
      col: 1,
      variant: 'text',
      label: 'Other / Personnel',
      tone: 'neutral',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'B25',
      address: 'B25',
      row: 25,
      col: 2,
      variant: 'metric',
      tone: 'input',
      editableKey: 'otherPersonnelY1',
      editableValue: inputs.otherPersonnelY1,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'C25',
      address: 'C25',
      row: 25,
      col: 3,
      variant: 'metric',
      tone: 'input',
      editableKey: 'otherPersonnelY2',
      editableValue: inputs.otherPersonnelY2,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'D25',
      address: 'D25',
      row: 25,
      col: 4,
      variant: 'metric',
      tone: 'input',
      editableKey: 'otherPersonnelY3',
      editableValue: inputs.otherPersonnelY3,
      prefix: '$',
      suffix: 'M',
      align: 'right',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'A26',
      address: 'A26',
      row: 26,
      col: 1,
      variant: 'section-header',
      label: 'EBITDA',
      tone: 'neutral',
      highlightGroup: 'case-study-all',
    },
    {
      id: 'B26',
      address: 'B26',
      row: 26,
      col: 2,
      variant: 'section-header',
      value: formatOneDecimal(outputs.ebitda[0]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=B15-B20',
      highlightGroup: 'case-study-all',
      emphasisLevel: 'high',
    },
    {
      id: 'C26',
      address: 'C26',
      row: 26,
      col: 3,
      variant: 'section-header',
      value: formatOneDecimal(outputs.ebitda[1]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=C15-C20',
      highlightGroup: 'case-study-all',
      emphasisLevel: 'high',
    },
    {
      id: 'D26',
      address: 'D26',
      row: 26,
      col: 4,
      variant: 'section-header',
      value: formatOneDecimal(outputs.ebitda[2]),
      prefix: '$',
      suffix: 'M',
      tone: 'formula',
      align: 'right',
      formula: '=D15-D20',
      highlightGroup: 'case-study-all',
      emphasisLevel: 'high',
    },
  ];
}
